<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue';
import { RouterLink, useRoute } from 'vue-router';
import { coverUrl, getAuthor, getWork } from '../services/openLibrary';
import type { AuthorResponse, WorkResponse } from '../types/open-library';

const route = useRoute(); const work = ref<WorkResponse|null>(null); const author = ref<AuthorResponse|null>(null); const loading = ref(true); const error = ref(''); const broken = ref(false); const controller = new AbortController();
const description = computed(() => { const d = work.value?.description; return typeof d === 'string' ? d : d?.value || 'No editorial description is available for this work.'; });
async function load() { loading.value = true; error.value=''; try { work.value = await getWork(`/works/${route.params.id}`, controller.signal); const key = work.value.authors?.[0]?.author.key?.split('/').pop(); if (key) author.value = await getAuthor(key, controller.signal); } catch(e) { if ((e as Error).name !== 'AbortError') error.value='This work could not be loaded.'; } finally { loading.value=false; } }
load(); onBeforeUnmount(()=>controller.abort());
</script>
<template><main class="detail-page"><RouterLink class="back-link" to="/">← Back to discovery</RouterLink><div v-if="loading" class="detail-loading"><div class="skeleton detail-cover"></div><div><div class="skeleton line"></div><div class="skeleton line short"></div></div></div><div v-else-if="error" class="state-panel"><div><span>WORK ERROR</span><h2>{{ error }}</h2></div><button @click="load">Retry</button></div><article v-else-if="work" class="book-detail"><div class="detail-cover-wrap"><img v-if="work.covers?.[0] && !broken" :src="coverUrl(work.covers[0],'L')" :alt="`Cover of ${work.title}`" @error="broken=true"/><div v-else class="cover-fallback large"><span>NO COVER</span><strong>{{ work.title.slice(0,1) }}</strong></div></div><div class="detail-copy"><div class="eyebrow">WORK / {{ route.params.id }}</div><h1>{{ work.title }}</h1><div class="author-block"><span>Primary author</span><strong>{{ author?.name || 'Unknown author' }}</strong><small v-if="author?.birth_date">{{ author.birth_date }}<template v-if="author.death_date"> — {{ author.death_date }}</template></small></div><p class="description">{{ description }}</p><div v-if="work.subjects?.length" class="subjects"><span v-for="subject in work.subjects.slice(0,10)" :key="subject">{{ subject }}</span></div></div></article></main></template>
